export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const SET_PRODUCT = "SET_PRODUCT";
export const SET_SKIP = "SET_SKIP";

export const GET_ARTIST_EVENTS_REQUEST = "GET_ARTIST_DETAILS_REQUEST";
export const GET_ARTIST_EVENTS_SUCCESS = "GET_ARTIST_DETAILS_SUCCESS";
export const GET_ARTIST_EVENTS_FAILURE = "GET_ARTIST_DETAILS_FAILURE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_PRODUCT_LOCAL = "ADD_PRODUCT_LOCAL";